// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALpMrk73GUPBn8yCjcCCaHxt11yEcooIU',
    appId: '1:283889365166:web:793c06402e5014058b3d3f',
    messagingSenderId: '283889365166',
    projectId: 'reclaimapp-fc1b9',
    authDomain: 'reclaimapp-fc1b9.firebaseapp.com',
    storageBucket: 'reclaimapp-fc1b9.appspot.com',
    measurementId: 'G-349JP6VJK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYAIJKGm7dFEoTRVkwpXft4B_-hAazSLQ',
    appId: '1:283889365166:android:8ee9b00118be78998b3d3f',
    messagingSenderId: '283889365166',
    projectId: 'reclaimapp-fc1b9',
    storageBucket: 'reclaimapp-fc1b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7epK212hrTYaBEUqGlYOBkHFLdVxXWhQ',
    appId: '1:283889365166:ios:398a9dcc5ea2b8418b3d3f',
    messagingSenderId: '283889365166',
    projectId: 'reclaimapp-fc1b9',
    storageBucket: 'reclaimapp-fc1b9.appspot.com',
    androidClientId: '283889365166-5jaatu9okqpvmepvva9hf60khs9fvh3v.apps.googleusercontent.com',
    iosClientId: '283889365166-kujmplpaaa4kvjaqs1nkl14c03oslc8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.prosAdminWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7epK212hrTYaBEUqGlYOBkHFLdVxXWhQ',
    appId: '1:283889365166:ios:398a9dcc5ea2b8418b3d3f',
    messagingSenderId: '283889365166',
    projectId: 'reclaimapp-fc1b9',
    storageBucket: 'reclaimapp-fc1b9.appspot.com',
    androidClientId: '283889365166-5jaatu9okqpvmepvva9hf60khs9fvh3v.apps.googleusercontent.com',
    iosClientId: '283889365166-kujmplpaaa4kvjaqs1nkl14c03oslc8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.prosAdminWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALpMrk73GUPBn8yCjcCCaHxt11yEcooIU',
    appId: '1:283889365166:web:793c06402e5014058b3d3f',
    messagingSenderId: '283889365166',
    projectId: 'reclaimapp-fc1b9',
    authDomain: 'reclaimapp-fc1b9.firebaseapp.com',
    storageBucket: 'reclaimapp-fc1b9.appspot.com',
    measurementId: 'G-349JP6VJK8',
  );
}
